-- Comprehensive CKA (Certified Kubernetes Administrator) Learning Content
-- This file contains detailed learning modules, quizzes, and lab exercises for Kubernetes administration

\c devops_practice;

-- Insert CKA/Kubernetes learning content
INSERT INTO learning.learning_content (title, content_type, tool_category, difficulty_level, content_data, prerequisites, estimated_duration) VALUES
('Kubernetes Fundamentals for CKA', 'module', 'kubernetes', 'beginner', 
'{"sections": [{"title": "What is Kubernetes?", "content": "Kubernetes is an open-source container orchestration platform that automates the deployment, scaling, and management of containerized applications across clusters of hosts.", "key_concepts": ["Container orchestration", "Declarative configuration", "Self-healing systems", "Horizontal scaling", "Service discovery and load balancing", "Rolling updates and rollbacks"]}, {"title": "Kubernetes Architecture", "content": "Kubernetes follows a master-worker architecture with control plane components managing the cluster and worker nodes running application workloads.", "control_plane_components": [{"name": "kube-apiserver", "description": "API server that exposes the Kubernetes API"}, {"name": "etcd", "description": "Distributed key-value store for cluster data"}, {"name": "kube-scheduler", "description": "Schedules pods to nodes based on resource requirements"}, {"name": "kube-controller-manager", "description": "Runs controller processes that regulate cluster state"}], "node_components": [{"name": "kubelet", "description": "Agent that runs on each node and manages containers"}, {"name": "kube-proxy", "description": "Network proxy that maintains network rules"}, {"name": "Container Runtime", "description": "Software responsible for running containers"}]}], "objectives": ["Understand Kubernetes architecture and components", "Learn core Kubernetes objects and their purposes", "Master essential kubectl commands", "Prepare for CKA certification exam"], "cka_exam_info": {"exam_duration": "2 hours", "passing_score": "66%", "format": "Performance-based tasks", "environment": "Command line only", "allowed_resources": ["kubernetes.io documentation"]}}', 
'{}', 60);

-- Module 2: Cluster Installation and Configuration
INSERT INTO learning.learning_content (title, content_type, tool_category, difficulty_level, content_data, prerequisites, estimated_duration) VALUES
('CKA: Cluster Installation and Configuration', 'module', 'kubernetes', 'intermediate',
'{"sections": [{"title": "Cluster Installation Methods", "content": "Learn different approaches to installing Kubernetes clusters for various environments.", "installation_methods": [{"method": "kubeadm", "description": "Official tool for bootstrapping Kubernetes clusters", "use_case": "Production clusters, learning, CKA exam"}, {"method": "kops", "description": "Kubernetes Operations tool for AWS", "use_case": "AWS production clusters"}, {"method": "kubespray", "description": "Ansible-based cluster deployment", "use_case": "On-premises and cloud deployments"}]}, {"title": "Installing with kubeadm", "content": "Step-by-step process for installing Kubernetes using kubeadm, the method used in CKA exam.", "prerequisites": ["Ubuntu 20.04+ or CentOS 7+", "2 GB RAM minimum", "2 CPUs minimum", "Network connectivity between nodes"], "installation_steps": [{"step": "Prepare the system", "commands": ["sudo swapoff -a", "sudo sed -i / swap / s/^/#/ /etc/fstab"]}, {"step": "Install container runtime", "commands": ["sudo apt-get update", "sudo apt-get install -y containerd"]}, {"step": "Install kubeadm, kubelet, kubectl", "commands": ["curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -", "sudo apt-get install -y kubelet kubeadm kubectl"]}]}], "objectives": ["Install Kubernetes cluster using kubeadm", "Configure cluster networking with CNI plugins", "Add worker nodes to the cluster", "Validate cluster installation and health"], "cka_exam_weight": "25%"}',
'{"Kubernetes Fundamentals for CKA"}', 75);

-- Module 3: Workloads and Scheduling
INSERT INTO learning.learning_content (title, content_type, tool_category, difficulty_level, content_data, prerequisites, estimated_duration) VALUES
('CKA: Workloads and Scheduling', 'module', 'kubernetes', 'intermediate',
'{"sections": [{"title": "Understanding Pods", "content": "Pods are the smallest deployable units in Kubernetes, containing one or more containers that share storage and network.", "pod_characteristics": ["Shared network namespace", "Shared storage volumes", "Containers in pod can communicate via localhost", "Pods are ephemeral and replaceable"]}, {"title": "Deployments and ReplicaSets", "content": "Deployments provide declarative updates for pods and ReplicaSets, managing application lifecycle and scaling.", "deployment_features": ["Declarative updates and rollbacks", "Scaling up and down", "Rolling updates with zero downtime", "Revision history and rollback capability"]}, {"title": "Pod Scheduling", "content": "Control where pods are scheduled using various scheduling mechanisms.", "scheduling_methods": [{"method": "Node Selector", "description": "Simple node selection using labels"}, {"method": "Node Affinity", "description": "More expressive node selection rules"}, {"method": "Taints and Tolerations", "description": "Prevent pods from being scheduled on certain nodes"}]}], "objectives": ["Create and manage pods, deployments, and other workloads", "Understand different workload controllers and their use cases", "Implement pod scheduling strategies", "Configure resource requests and limits"], "cka_exam_weight": "15%"}',
'{"CKA: Cluster Installation and Configuration"}', 80);

-- Quiz 1: Kubernetes Fundamentals
INSERT INTO learning.learning_content (title, content_type, tool_category, difficulty_level, content_data, prerequisites, estimated_duration) VALUES
('CKA Fundamentals Quiz', 'quiz', 'kubernetes', 'beginner',
'{"questions": [{"question": "Which component stores all cluster data in Kubernetes?", "options": ["kube-apiserver", "etcd", "kube-scheduler", "kubelet"], "correct": 1, "explanation": "etcd is the distributed key-value store that stores all cluster data including configuration, state, and metadata."}, {"question": "What is the smallest deployable unit in Kubernetes?", "options": ["Container", "Pod", "Service", "Deployment"], "correct": 1, "explanation": "A Pod is the smallest deployable unit in Kubernetes and can contain one or more containers."}, {"question": "Which kubectl command shows detailed information about a resource?", "options": ["kubectl get", "kubectl describe", "kubectl explain", "kubectl show"], "correct": 1, "explanation": "kubectl describe provides detailed information about a specific resource including events and status."}, {"question": "What is the primary purpose of a Service in Kubernetes?", "options": ["Store configuration data", "Provide stable network endpoint for pods", "Manage container images", "Schedule pods to nodes"], "correct": 1, "explanation": "Services provide stable network endpoints and load balancing for accessing pods, which have ephemeral IP addresses."}, {"question": "Which tool is commonly used for bootstrapping Kubernetes clusters?", "options": ["kubectl", "kubeadm", "kubelet", "kube-proxy"], "correct": 1, "explanation": "kubeadm is the official tool for bootstrapping Kubernetes clusters and is used in the CKA exam."}], "passing_score": 80, "time_limit": 900}',
'{"Kubernetes Fundamentals for CKA"}', 20);

-- Lab 1: CKA Cluster Setup Lab
INSERT INTO learning.learning_content (title, content_type, tool_category, difficulty_level, content_data, prerequisites, estimated_duration) VALUES
('CKA Cluster Setup Lab', 'lab', 'kubernetes', 'intermediate',
'{"description": "Hands-on lab for setting up a Kubernetes cluster using kubeadm, similar to CKA exam environment", "learning_objectives": ["Install Kubernetes cluster using kubeadm", "Configure cluster networking", "Join worker nodes to the cluster", "Validate cluster functionality"], "environment": {"type": "kubernetes", "nodes": [{"name": "master", "role": "control-plane", "specs": "2 CPU, 4GB RAM"}, {"name": "worker1", "role": "worker", "specs": "2 CPU, 2GB RAM"}]}, "tasks": [{"title": "Prepare All Nodes", "description": "Configure prerequisites on all nodes", "instructions": ["Disable swap on all nodes", "Install container runtime", "Install kubeadm, kubelet, and kubectl"], "commands": ["sudo swapoff -a", "sudo apt-get install -y containerd", "sudo apt-get install -y kubelet kubeadm kubectl"]}, {"title": "Initialize Control Plane", "description": "Initialize the Kubernetes control plane on master node", "instructions": ["Run kubeadm init with appropriate parameters", "Configure kubectl for regular user"], "commands": ["sudo kubeadm init --pod-network-cidr=10.244.0.0/16", "mkdir -p $HOME/.kube", "sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config"]}, {"title": "Install Network Plugin", "description": "Install Flannel CNI plugin for pod networking", "commands": ["kubectl apply -f https://raw.githubusercontent.com/flannel-io/flannel/master/Documentation/kube-flannel.yml"]}], "completion_criteria": ["Kubernetes cluster with master and worker nodes", "All nodes in Ready state", "All system pods running", "Test application deployed and accessible"]}',
'{"CKA: Cluster Installation and Configuration"}', 120);

-- Assessment: CKA Practice Exam
INSERT INTO learning.learning_content (title, content_type, tool_category, difficulty_level, content_data, prerequisites, estimated_duration) VALUES
('CKA Practice Assessment', 'quiz', 'kubernetes', 'advanced',
'{"description": "Practice assessment simulating CKA exam format with performance-based tasks", "exam_format": "Performance-based tasks in live Kubernetes environment", "questions": [{"question": "Create a pod named web-pod using nginx:1.20 image. The pod should have a label app=web and should be scheduled only on nodes with label disktype=ssd.", "type": "practical", "points": 4, "solution_approach": ["Create pod YAML with nodeSelector", "Apply the configuration", "Verify pod is scheduled correctly"], "validation": "kubectl get pod web-pod -o wide"}, {"question": "Create a deployment named api-deployment with 3 replicas using nginx:alpine image. Configure resource requests of 100m CPU and 128Mi memory for each container.", "type": "practical", "points": 6, "solution_approach": ["Create deployment YAML with resource requests", "Set replica count to 3", "Apply and verify deployment"], "validation": "kubectl get deployment api-deployment"}, {"question": "A pod named broken-pod is not starting. Troubleshoot and fix the issue.", "type": "troubleshooting", "points": 8, "common_issues": ["Image pull errors", "Resource constraints", "Configuration syntax errors"], "validation": "kubectl get pod broken-pod"}], "time_limit": 7200, "passing_score": 66, "exam_tips": ["Use kubectl documentation", "Practice imperative commands for speed", "Always verify your solutions", "Manage time effectively"], "certification": {"name": "CKA Practice Certification", "description": "Demonstrates readiness for the Certified Kubernetes Administrator exam"}}',
'{"CKA Fundamentals Quiz", "CKA Cluster Setup Lab", "CKA: Workloads and Scheduling"}', 120);